---

- name: install node
  homebrew: name={{item}} state=latest
  with_items:
    - node
    - nvm

- name: create nvm directory
  file:
    path: "{{item}}"
    state: directory
  with_items:
    - ~/.nvm

- name: copy nvm-exec to NVM's working directory
  shell: cp $(brew --prefix nvm)/nvm-exec ~/.nvm/ creates=~/.nvm/nvm-exec

- name: place the different configuration files into place
  become: yes
  copy:
    src: "bashrc.{{item}}.sh"
    dest: "/etc/bashrc.{{item}}.sh"
    owner: root
    group: wheel
    mode: 0644
  with_items:
    - node

- name: add the different configuration files to bashrc
  become: yes
  lineinfile: >
    dest=/etc/bashrc
    regexp="bashrc.{{item}}.sh"
    line="if [ -f /etc/bashrc.{{item}}.sh ]; then . /etc/bashrc.{{item}}.sh; fi"
    state=present
    create=true
  with_items:
    - node

- name: install other node versions via nvm
  shell: . /etc/bashrc.node.sh; nvm install {{item}}
  with_items: "{{node_versions}}"

- name: st the default node version
  shell: . /etc/bashrc.node.sh; nvm alias default {{default_node_version}}
